#!/bin/bash

echo "🎵 Spotify Audio Features - Backend Explorer"
echo "============================================"
echo ""
echo "Backend is running at: http://localhost:8000"
echo ""
echo "Available endpoints:"
echo "  📖 API Docs (Swagger):  http://localhost:8000/docs"
echo "  📖 API Docs (ReDoc):    http://localhost:8000/redoc"
echo "  🎵 Analyze Audio:       POST http://localhost:8000/analyze"
echo "  📜 View History:        GET http://localhost:8000/history"
echo ""
echo "Quick Commands:"
echo "  1. View database:       sqlite3 backend/songs.db 'SELECT * FROM songs;'"
echo "  2. Test analyze:        curl -X POST -F 'file=@test.wav' http://localhost:8000/analyze"
echo "  3. View history:        curl http://localhost:8000/history"
echo ""
echo "Opening API docs in browser..."
